#############################################################################
# Makefile for building: dropbox
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  dropbox.pro
# Template: subdirs
# Command: C:\Qt\5.9.1\mingw53_32\bin\qmake.exe -o Makefile dropbox.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.9.1\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.9.1\mingw53_32\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.9.1\mingw53_32\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-common \
		sub-server \
		sub-client


sub-common-qmake_all:  FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd common\ && $(MAKE) -f Makefile qmake_all
sub-common: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-common-make_first-ordered: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-common-make_first: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-common-all-ordered: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-common-all: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-common-clean-ordered: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-common-clean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-common-distclean-ordered: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-common-distclean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-common-install_subtargets-ordered: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-common-install_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-common-uninstall_subtargets-ordered: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-common-uninstall_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-server-qmake_all: sub-common-qmake_all FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd server\ && $(MAKE) -f Makefile qmake_all
sub-server: FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-server-make_first-ordered: sub-common-make_first-ordered  FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-server-make_first: FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-server-all-ordered: sub-common-all-ordered  FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-server-all: FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-server-clean-ordered: sub-common-clean-ordered  FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-server-clean: FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-server-distclean-ordered: sub-common-distclean-ordered  FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-server-distclean: FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-server-install_subtargets-ordered: sub-common-install_subtargets-ordered  FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-server-install_subtargets: FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-server-uninstall_subtargets-ordered: sub-common-uninstall_subtargets-ordered  FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-server-uninstall_subtargets: FORCE
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-client-qmake_all: sub-server-qmake_all FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd client\ && $(MAKE) -f Makefile qmake_all
sub-client: FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-client-make_first-ordered: sub-server-make_first-ordered  FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-client-make_first: FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-client-all-ordered: sub-server-all-ordered  FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-client-all: FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-client-clean-ordered: sub-server-clean-ordered  FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-client-clean: FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-client-distclean-ordered: sub-server-distclean-ordered  FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-client-distclean: FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-client-install_subtargets-ordered: sub-server-install_subtargets-ordered  FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-client-install_subtargets: FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-client-uninstall_subtargets-ordered: sub-server-uninstall_subtargets-ordered  FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-client-uninstall_subtargets: FORCE
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: dropbox.pro ../../../../Qt/5.9.1/mingw53_32/mkspecs/win32-g++/qmake.conf ../../../../Qt/5.9.1/mingw53_32/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/qdevice.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/device_config.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/common/g++-base.conf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/common/angle.conf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/common/sanitize.conf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/qconfig.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/qt_config.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/win32-g++/qmake.conf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/spec_post.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/toolchain.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/default_pre.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/win32/default_pre.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/default_post.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/precompile_header.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/warn_on.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/file_copies.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/win32/windows.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/exceptions.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/yacc.prf \
		../../../../Qt/5.9.1/mingw53_32/mkspecs/features/lex.prf \
		dropbox.pro
	$(QMAKE) -o Makefile dropbox.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/spec_pre.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/qdevice.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/device_config.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/common/g++-base.conf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/common/angle.conf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/common/sanitize.conf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/common/gcc-base.conf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/qconfig.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/qt_functions.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/qt_config.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/win32-g++/qmake.conf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/spec_post.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/toolchain.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/default_pre.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/win32/default_pre.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/resolve_config.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/default_post.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/qml_debug.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/precompile_header.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/warn_on.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/qmake_use.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/file_copies.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/win32/windows.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/exceptions.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/yacc.prf:
../../../../Qt/5.9.1/mingw53_32/mkspecs/features/lex.prf:
dropbox.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile dropbox.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-common-qmake_all sub-server-qmake_all sub-client-qmake_all FORCE

make_first: sub-common-make_first-ordered sub-server-make_first-ordered sub-client-make_first-ordered  FORCE
all: sub-common-all-ordered sub-server-all-ordered sub-client-all-ordered  FORCE
clean: sub-common-clean-ordered sub-server-clean-ordered sub-client-clean-ordered  FORCE
distclean: sub-common-distclean-ordered sub-server-distclean-ordered sub-client-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-common-install_subtargets-ordered sub-server-install_subtargets-ordered sub-client-install_subtargets-ordered FORCE
uninstall_subtargets: sub-common-uninstall_subtargets-ordered sub-server-uninstall_subtargets-ordered sub-client-uninstall_subtargets-ordered FORCE

sub-common-debug_ordered:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-server-debug_ordered: sub-common-debug_ordered 
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-client-debug_ordered: sub-server-debug_ordered 
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-common-debug_ordered sub-server-debug_ordered sub-client-debug_ordered

sub-common-release_ordered:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-server-release_ordered: sub-common-release_ordered 
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-client-release_ordered: sub-server-release_ordered 
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-common-release_ordered sub-server-release_ordered sub-client-release_ordered

sub-common-check_ordered:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-server-check_ordered: sub-common-check_ordered 
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-client-check_ordered: sub-server-check_ordered 
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-common-check_ordered sub-server-check_ordered sub-client-check_ordered

sub-common-benchmark_ordered:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\common\common.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-server-benchmark_ordered: sub-common-benchmark_ordered 
	@if not exist server\ mkdir server\ & if not exist server\ exit 1
	cd server\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\server\server.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-client-benchmark_ordered: sub-server-benchmark_ordered 
	@if not exist client\ mkdir client\ & if not exist client\ exit 1
	cd client\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\eadakle\Documents\dropbox\client\client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-common-benchmark_ordered sub-server-benchmark_ordered sub-client-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

